name: flutter_xupdate_ae
description: A Flutter plugin for XUpdate(Android Version Update Library).
version: 3.1.0
homepage: https://github.com/aaron0713/flutter_xupdate_ae
repository: https://github.com/aaron0713/flutter_xupdate_ae
issue_tracker: https://github.com/aaron0713/flutter_xupdate_ae/issues

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.xuexiang.flutter_xupdate
        pluginClass: FlutterXUpdatePlugin
